sudo: required

services:
  - docker

before_install:
  - travis_wait 30 docker build -t shushen/tox .

script:
  - docker run --rm shushen/tox python2.7 --version
  - docker run --rm shushen/tox python3.4 --version
  - docker run --rm shushen/tox python3.5 --version
  - docker run --rm shushen/tox python3.6 --version

  - docker run --rm shushen/tox test -f /root/.pyenv/versions/2.7.14/bin/tox
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.4.8/bin/tox
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.5.5/bin/tox
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.6.5/bin/tox

  - docker run --rm shushen/tox test -f /root/.pyenv/versions/2.7.14/bin/pip
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.4.8/bin/pip
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.5.5/bin/pip
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.6.5/bin/pip
